jobs:
  deploy:
  name: Deploy to production
  steps:
  ---
  - name: "configure AWS credentials"
    uses: aws-actions/configure
    with:
      role-to-assume:
      role-session-name:
      aws-region: us-east-2
  
  - name: "deploy to app"
    run: |
      "ec2 deploy script to use"